apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "helloworld-ingress.name" . }}
spec:
  secretName: {{ template "helloworld-ingress.name" . }}
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
  commonName:
  dnsNames:
  {{- range .Values.ingress.hosts }}
    - http{{ if $.Values.ingress.tls }}s{{ end }}://{{ . }}
  {{- end }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      {{- range .Values.ingress.hosts }}
        - http{{ if $.Values.ingress.tls }}s{{ end }}://{{ . }}
      {{- end }}